### ISSUE TITLE
Support inspection of a specific partition

### ISSUE THREAD

**Issue by BoydSharrockVerr** [operatr-io/community#1]
I have been looking at the inspect topic feature. 

It's very handy that operatr has the ability to view recent messages on a topic - however as far as I can tell it is not possible to choose a specific partition.

The background is we have a support case where we believe the issue is connected to the data on a specific partition.

Is it possible operatr could support viewing the messages on a specific partition - potentially from offset 0.

**Comment by d-t-w** [comment]
Thank-you Boyd, we had this in mind and will bump it up the backlog!

**Comment by d-t-w** [comment]
Thanks again @BoydSharrockVerr, this is resolved in release #4.

**Comment by d-t-w** [comment]
Topic inspection without specifying partition or offset:

![image](https://user-images.githubusercontent.com/2832467/67729003-886b5880-fa43-11e9-9c49-2334ac53f453.png)

Topic inspection with a specified partition and offset:

![image](https://user-images.githubusercontent.com/2832467/67729017-94efb100-fa43-11e9-8d8a-4f894ff0bbf6.png)
