### ISSUE TITLE
Problems with first time run

### ISSUE THREAD

**Issue by saubury** [operatr-io/community#2]
Hi

Upon downloading the first-time instructions on the welcome page are

`docker run -p 3000:3000 --e BOOTSTRAP=[X] operatr/operatr:latest`

I think this should be either `-e` or `--env`

However, even with a local cluster running using what I think is the minimal setup (basic Confluent 5.3.0 platform) 

`docker run -p 3000:3000 -e BOOTSTRAP=localhost:9092 -e TRIAL_CODE=CodeHere operatr/operatr:latest`

```
docker run -p 3000:3000 -e BOOTSTRAP=localhost:9092 operatr/operatr:latest
01:01:25.143 INFO  [main] operatr.system ? starting operatr
01:01:25.418 INFO  [main] operatr.append.riemann ? Riemann not configured.
01:01:55.427 ERROR [main] operatr.system ? uncaught exception on main
clojure.lang.ExceptionInfo: Error on key [:kafka/topic :operatr/metric-topic] when building system
	at integrant.core$build_exception.invokeStatic(core.cljc:283)
```

**Comment by d-t-w** [comment]
Hi Simon, thanks for raising a ticket.

1. You're correct, it should be -e or --env. Site updated.

2. This looks like a docker network issue. OPERATR will run against any Kafka Cluster with at least 3 nodes, but in this case it looks like it can't access Kafka running on localhost.

In any case the error should be clearer. In the meantime I've created a sample docker-compose and local.env for evaluating OPERATR in a local enviroment:

https://github.com/operatr-io/local

Would you mind giving that a go? You should be able to run OPERATR against Confluent 5.3.0 Platform as well as long as the container is on the same network as the brokers and there's at minimum a 3-node cluster.

I'll be updating the installation instructions shortly with examples of this, instacluster, MSK, Confluent Cloud, and configuring a Schema Registry for inspecting topics with AVRO data.

**Comment by saubury** [comment]
Thanks Derek for cleaning up the first time docs. 

It wasn't clear to me that a  3-node Apache Kafka cluster was required.  Yes, a more concise error message would be helpful for new users 

I'll give the other repo a try - thanks!

**Comment by d-t-w** [comment]
Great, thanks Simon. Let us know how you go with operatr/local.

The installation page has been updated with quick examples of configuration for Amazon MSK, Instaclustr, Confluent Cloud, Schema Regsitry, and a few more combinations.

Finally - I forgot there's a REPLICATION_FACTOR environment variable that you could set to 1 if you'd like to run against a single node setup. That had been disabled but will be back in our release tomorrow.

**Comment by saubury** [comment]
Thanks Derek - I had a few problems with the local install .. I'll raise an issue and PR in that repo

**Comment by d-t-w** [comment]
Thanks Simon, your help is very much appreciated.
