### ISSUE TITLE
Add Long deserializer to topic inspector

### ISSUE THREAD

**Issue by BoydSharrockVerr** [operatr-io/community#3]
Is is possible to add support for Long values on the Value Deserializer in the Topic inspector?

**Comment by d-t-w** [comment]
Boyd, thanks for raising this  - we'll wrap up a new release for you tomorrow.

**Comment by d-t-w** [comment]
Thanks @BoydSharrockVerr, this is now resolved in Operatr #18.

We included support for all the missing basic deserializers in topic inspect (Long, Float, Short, Double, Integer)
