### ISSUE TITLE
The page looks fine first day, but when next day, pages loading icons keep spinning and all metrics are empty

### ISSUE THREAD

**Issue by xuwangpalo** [operatr-io/community#4]

**Comment by d-t-w** [comment]
Hi Xuwang, thanks for the report.

Could you provide some further information:

1. What version of Kafka are you using?
2. How many brokers, topics, groups does the cluster have?

Can you provide either a screenshot or information from the admin/about page of your Operatr installation:

https://demo.operatr.io/#/admin/about

Particularly helpful is the version of Operatr you are using, and  the Collect Snapshots min/mean/max.

Finally, do you see any errors in the logs?

Thanks, if you would prefer not to post on github please send an email to support@operatr.io  and we'll get right onto it!

**Comment by xuwangpalo** [comment]
Probably due to out of disk. I will close this for now. Thanks!

**Comment by d-t-w** [comment]
That would do it! Any more issues just let us know. :)
