### ISSUE TITLE
Operatr Memory Utilization is more than 10Gi when deployed on Azure Kubernetes Service

### ISSUE THREAD

**Issue by sonujose** [operatr-io/community#7]
I have deployed Operatr dashboard on Azure Kubernetes cluster and seeing huge memory utilization, most times it is more than 10Gi.
 
The Kafka Cluster provider is Instaclustr.

I couldn't find any documentation that explains about volume mounts for the RocksDB.

Using the official Operatr Docker Image - https://hub.docker.com/r/operatr/operatr

**Comment by d-t-w** [comment]
Hi Sonu.

Have you restricted the resources of the kubernetes pod that Operatr is deployed within?

e.g.

````
resources:
      requests:
        memory: ""
        cpu: ""
````

We recommend 2GB heap and 1VCPU. Operatr is configured to use 70% of the memory available to the docker container, so it's important to constrain those resources to the pod.

**Comment by sonujose** [comment]
Right now I have set the memory request to be 4Gi and Limit to be 6Gi, then only it is working. Any values less than this is evicting. Even after some time, even this limit will exceed and Pod will evict.
```
  limits:
    cpu: 1
    memory: 6Gi
  requests:
    cpu: 1
    memory: 4Gi
```
Practically allocating these much memory is not a viable solution. If we can mount the data path to an external persistent volume that would be helpful. 

Are you guys using any databases or is there any way we can use our custom database and integrate that to the deployment?

**Comment by d-t-w** [comment]
> Right now I have set the memory request to be 4Gi and Limit to be 6Gi, then only it is working. Any values less than this is evicting.

Can you tell me the exception that occurs on eviction? It isn't clear to me if you are experiencing memory issues (either on-heap or off-heap) or disk issues.

My first suggestion to you would be to run Operatr with 2GB heap and 1cpu, with the environment flag **IN_MEMORY_METRICS** set to true. Explanation below.

> Practically allocating these much memory is not a viable solution

We have a single instance of Operatr running multi-cluster in AWS for three weeks, monitoring 3 Clusters, 40 brokers, 40 topics, and 40 groups on 2GB heap and 1vcpu, so I'm confident that the volume of memory allocated is not the issue, and we wil be able to get you running with 2GB.

**Operatr Memory Consumption**

The Docker container starts a java process with:

```
CMD java -XX:InitialRAMPercentage=70 -XX:MaxRAMPercentage=70 -jar /opt/operatr/lib/operatr.jar
```

An Operatr running in default mode (IN_MEMORY_METRICS=false) will use JVM Heap + Off-Heap (RocksDB Caches) + Disk (RocksDB DB records).

Assuming 2GB memory allocated to the container, that would be broken down as:

* **1.4GB** (70%) for JVM Heap to run Operatr.
* **200MB** (roughly) for Off-Heap RocksDB caches.
* Leaving **400MB** for the OS within the container.

RocksDB will also write data to disk, by default into a directory called **/tmp/kafka-streams/**. If you want to continue to run in default mode you could mount that to external disk, though it's not important for it to be persistent. Ephemeral disk is fine as it is rebuilt from topics on restart.

It is important that your container can write to disk though, and you have enough disk allocated in default mode. We suggest up to **2GB**.

If you run with the environment variable **IN_MEMORY_METRICS=true** set then Operatr doesn't use RocksDB at all, everything is on-heap in the JVM. No off-heap, no disk. That's probably a simpler provisioning method for you to experiment with and has no practical impact on single-cluster operation.

**Comment by sonujose** [comment]
Thanks for the information!!
Right now the memory utilization is around - 4Gi. I am using the default configurations.
```
k top pods -n operatr
NAME                                    CPU(cores)   MEMORY(bytes)
dashboard-operatr-io-6fbd5b6c4f-vsp4s   19m          4793Mi
```

**Comment by d-t-w** [comment]
Hi, can you let me know.

1. Are you still experiencing a problem?
2. If so, what error is raised on eviction?
3. Have you tried running with IN_MEMORY_METRICS?

If the answer is yes to those questions, can you email support@operatr.io with a screenshot of the admin/about page, particularly the performance graphs, and let us know how many brokers, topics, and groups are active in your cluster.

**Comment by d-t-w** [comment]
Can you also provide the output from:

- run `kubectl describe <EVICTED_POD>` to find out the reason why it was evicted in the events.
- run `kubectl describe <THE_NODE_WHERE_THE_POD_WAS_EVICTED>` to check Conditions. 
- run `kubectl get events`. <- anything related to the specific pod eviction in there?

**Comment by sonujose** [comment]
Thanks Derek. Everything working perfect. Now I have the memory utilization in the limits and is stable for a week.

With the below configuration, the utilization is just 1865Mi and that solved the purpose.
```
  limits:
    cpu: 1
    memory: 2Gi
  requests:
    cpu: 1
    memory: 2Gi
```
The catch is the QOS class I think, now with request and limit are same so the QOS class is `Guaranteed`.

**Comment by d-t-w** [comment]
Thank-you so much for following up Sonu, your help is appreciated and I'm glad that Operatr has been stable for a week in your Azure/K8s world.

We will take these learnings and include them in our documentation shortly, that's the next big task - updating our docs!
